### ISSUE TITLE
Why is this so trash?

### ISSUE THREAD

**Issue by bytewise43** [thuner2007/cdx#1]
Pls fix!!

Why is this a react project when it should be a npm package?
Why are you redesigning divs?
Why is a random colour a desired feature?
Overthink your strategy on how to build components that should be usable in various contexts, your components seem very specific

**Comment by thuner2007** [comment]
💔

**Comment by thuner2007** [comment]
what should i use then?
Because i don' want to make a flex div every time
Because it's usefull to see the border of the components when using them and random colours do differentiate the borders.

**Comment by bytewise43** [comment]
> what should i use then? Because i don' want to make a flex div every time Because it's usefull to see the border of the components when using them and random colours do differentiate the borders.

Make css classes that ship with your package or just use tailwind then it is a breeze.

**Comment by thuner2007** [comment]
ky$
